export const getProductFields = (brandOptions = [], product = {}) => [
  {
    name: "name",
    label: "Product Name",
    type: "text",
    placeholder: "Enter product name",
    required: true,
    defaultValue: product.name || "",
  },
  {
    name: "description",
    label: "Product Description",
    type: "text",
    placeholder: "Enter description",
    required: false,
    defaultValue: product.description || "",
  },
  {
    name: "brand",
    label: "Brand",
    type: "select",
    placeholder: "Select brand",
    required: true,
    options: brandOptions,
    defaultValue: product.brand || "",
  },
  {
    name: "model",
    label: "Model",
    type: "text",
    placeholder: "Enter model name",
    required: false,
    defaultValue: product.model || "",
  },
  {
    name: "returnPolicy",
    label: "Return Policy",
    type: "text",
    placeholder: "Enter return policy (if any)",
    required: false,
    defaultValue: product.returnPolicy || "",
  },
  {
    name: "codAvailable",
    label: "Cash on Delivery Available?",
    type: "select",
    placeholder: "Select an option",
    required: true,
    options: [
      { label: "Yes", value: true },
      { label: "No", value: false },
    ],
    defaultValue:
      product.codAvailable !== undefined ? product.codAvailable : "",
  },
  {
    name: "warranty",
    label: "Warranty",
    type: "text",
    placeholder: "Enter warranty info (optional)",
    required: false,
    defaultValue: product.warranty || "",
  },
  {
    name: "offerPercentage",
    label: "Offer Percentage",
    type: "number",
    placeholder: "Enter offer percentage",
    required: false,
    defaultValue: product.offerPercentage || "",
  },
];
